# Generated by Django 5.1.4 on 2025-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
