# Generated by Django 5.1.6 on 2025-02-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrada', '0002_remove_producto_descripcion_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talle',
            field=models.CharField(default='M', max_length=3),
        ),
    ]
